name: API Test Workflow

on:
  push:
    branches: [ "main", "master", "develop" ]  # Agregamos develop para más flexibilidad
  pull_request:
    branches: [ "main", "master", "develop" ]
  schedule:
    - cron: '0 0 * * *'  # Ejecutar diariamente a medianoche
  workflow_dispatch:  # Permite la ejecución manual desde la interfaz de GitHub

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Build Docker image
      run: |
        echo "🐳 Building Docker image..."
        docker build -t api-tests .
      
    - name: Run tests in Docker
      run: |
        echo "🧪 Running tests in Docker container..."
        docker run --name test-container api-tests
        docker cp test-container:/app/allure-results ./allure-results
      
    - name: Get Allure history
      uses: actions/checkout@v3
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages
        fetch-depth: 0
    
    - name: Generate Allure Report
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: allure-results
        allure_history: allure-history
        keep_reports: 20
        
    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-history
        force_orphan: true